Add Russian translations
UkoeHB/Monero-RCT-report pull request #9
Opened 2021-04-29 17:41 UTC by v1docq47

Added full translation of Zero to Monero: Second Edition into Russian
Link to translation in Overleaf - https://www.overleaf.com/read/gvdnrxqgmksy

2021-04-30 16:39 UTC, UkoeHB requested changes

2021-04-30 16:39 UTC, UkoeHB commented on translations/ru/main.tex
> +{\par\centering \textsc{\LARGE Опубликовано 4 апреля 2004 г. (v2.0.0)}\par}
2004 -> 2020

2021-04-30 16:39 UTC, UkoeHB commented on translations/ru/main.tex
> +{\par\centering \textsc{\large koe\footnote{ukoe@protonmail.com}, Курт M. Алонсо\footnote{kurt@oktav.se}, Саранг Ноезер\footnote{sarang.noether@protonmail.com}}%\\(for questions and comments, please
Do you want to add 'translated by'?

2021-05-01 17:10 UTC, v1docq47 commented on translations/ru/main.tex
> +{\par\centering \textsc{\LARGE Опубликовано 4 апреля 2004 г. (v2.0.0)}\par}
Thanks! Fixed!

2021-05-01 17:12 UTC, v1docq47 commented on translations/ru/main.tex
> +{\par\centering \textsc{\large koe\footnote{ukoe@protonmail.com}, Курт M. Алонсо\footnote{kurt@oktav.se}, Саранг Ноезер\footnote{sarang.noether@protonmail.com}}%\\(for questions and comments, please
Added \linebreak Перевод выполнен v1docq47\footnote{chiptune@protonmail.ch}

2021-05-02 19:47 UTC, merged